CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC;

CREATE TABLE IF NOT EXISTS public.provinces (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  exam_mode text,
  max_score smallint NOT NULL DEFAULT 750 CHECK (max_score > 0)
);

CREATE TABLE IF NOT EXISTS public.schools (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  province_id integer NOT NULL REFERENCES public.provinces(id),
  city text NOT NULL,
  level text NOT NULL CHECK (level IN ('985','211','双一流','一本','二本','本科','专科')),
  school_type text,
  latitude numeric(9,6),
  longitude numeric(9,6),
  official_url text,
  admissions_url text,
  links_verified_at timestamptz,
  links_source_url text,
  features jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_school_name_province UNIQUE (name, province_id)
);
CREATE INDEX IF NOT EXISTS idx_school_location ON public.schools(province_id, city);

CREATE TABLE IF NOT EXISTS public.majors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE,
  name text NOT NULL,
  category text NOT NULL,
  holland_types jsonb NOT NULL DEFAULT '[]'::jsonb,
  career_tags jsonb NOT NULL DEFAULT '[]'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_major_category ON public.majors(category);

CREATE TABLE IF NOT EXISTS public.school_majors (
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  major_id bigint NOT NULL REFERENCES public.majors(id) ON DELETE CASCADE,
  discipline_rating text,
  is_featured smallint NOT NULL DEFAULT 0 CHECK (is_featured IN (0,1)),
  PRIMARY KEY (school_id, major_id)
);
CREATE INDEX IF NOT EXISTS idx_school_majors_major ON public.school_majors(major_id);

CREATE TABLE IF NOT EXISTS public.admission_scores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  province_id integer NOT NULL REFERENCES public.provinces(id),
  year smallint NOT NULL,
  subject_group text NOT NULL,
  batch text,
  min_score smallint,
  min_rank integer,
  enrollment_count integer,
  CONSTRAINT uk_admission_record UNIQUE NULLS NOT DISTINCT (school_id, province_id, year, subject_group, batch)
);
CREATE INDEX IF NOT EXISTS idx_admission_lookup ON public.admission_scores(province_id, year, subject_group, min_rank);
CREATE INDEX IF NOT EXISTS idx_admission_scores_school ON public.admission_scores(school_id);

CREATE TABLE IF NOT EXISTS public.data_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type text NOT NULL CHECK (source_type IN ('school_list','admission','major','manual')),
  title text NOT NULL,
  source_url text NOT NULL,
  source_year smallint NOT NULL,
  publisher text NOT NULL,
  published_at date,
  effective_at date,
  collected_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_source_url_year UNIQUE (source_url, source_year)
);

CREATE TABLE IF NOT EXISTS public.admission_programs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_key text NOT NULL UNIQUE,
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  province_id integer NOT NULL REFERENCES public.provinces(id),
  year smallint NOT NULL,
  subject_group text NOT NULL,
  education_level text NOT NULL CHECK (education_level IN ('本科','专科')),
  admission_category text NOT NULL DEFAULT '普通类',
  batch text NOT NULL,
  plan_type text NOT NULL DEFAULT '普通计划',
  eligibility_requirement text,
  recommendation_eligible smallint NOT NULL DEFAULT 0 CHECK (recommendation_eligible IN (0,1)),
  recommendation_exclusion_reason text,
  unit_type text NOT NULL DEFAULT 'exact_major' CHECK (unit_type IN ('exact_major','major_group','school_line')),
  major_name text NOT NULL,
  raw_school_name text NOT NULL,
  raw_unit_name text NOT NULL,
  unit_code text,
  subject_requirement text,
  school_code text,
  major_code text,
  min_score smallint,
  min_rank integer,
  enrollment_count integer,
  source_id bigint REFERENCES public.data_sources(id)
);
CREATE INDEX IF NOT EXISTS idx_program_school_fk ON public.admission_programs(school_id);
CREATE INDEX IF NOT EXISTS idx_program_source_fk ON public.admission_programs(source_id);
CREATE INDEX IF NOT EXISTS idx_program_lookup ON public.admission_programs(province_id, year, subject_group, education_level, recommendation_eligible, min_rank);

CREATE TABLE IF NOT EXISTS public.student_profiles (
  id uuid PRIMARY KEY,
  student_name text NOT NULL,
  province_id integer REFERENCES public.provinces(id),
  subject_group text,
  selected_subjects jsonb NOT NULL DEFAULT '[]'::jsonb,
  score smallint,
  province_rank integer,
  holland_result jsonb,
  city_preferences jsonb,
  current_stage text NOT NULL DEFAULT 'basic_info' CHECK (current_stage IN ('basic_info','assessment_entry','assessment','recommendation')),
  planning_mode text NOT NULL DEFAULT 'application' CHECK (planning_mode IN ('exploration','application')),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_student_profiles_province ON public.student_profiles(province_id);

CREATE TABLE IF NOT EXISTS public.profile_score_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  exam_name text NOT NULL,
  exam_date date NOT NULL,
  score smallint,
  province_rank integer,
  note text,
  is_current smallint NOT NULL DEFAULT 0 CHECK (is_current IN (0,1)),
  origin_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_score_snapshot_timeline ON public.profile_score_snapshots(profile_id, exam_date, id);
CREATE INDEX IF NOT EXISTS idx_score_snapshot_current ON public.profile_score_snapshots(profile_id, is_current);

CREATE TABLE IF NOT EXISTS public.profile_assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  perspective text NOT NULL CHECK (perspective IN ('student','parent')),
  answers jsonb NOT NULL,
  scores jsonb NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed')),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_profile_assessment UNIQUE (profile_id, perspective)
);

CREATE TABLE IF NOT EXISTS public.profile_preferences (
  profile_id uuid PRIMARY KEY REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  postgraduate_tendency text NOT NULL CHECK (postgraduate_tendency IN ('employment','open','planned','uncertain')),
  family_conditions jsonb NOT NULL,
  student_ranking jsonb NOT NULL,
  parent_ranking jsonb NOT NULL,
  final_weights jsonb NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','completed')),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.recommendation_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  school_id bigint NOT NULL REFERENCES public.schools(id),
  major_id bigint REFERENCES public.majors(id),
  recommendation_level text NOT NULL CHECK (recommendation_level IN ('冲','稳','保')),
  match_score numeric(5,2) NOT NULL,
  reason jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_recommendation_profile ON public.recommendation_results(profile_id, recommendation_level);
CREATE INDEX IF NOT EXISTS idx_recommendation_school ON public.recommendation_results(school_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_major ON public.recommendation_results(major_id);

CREATE TABLE IF NOT EXISTS public.recommendation_snapshots (
  profile_id uuid PRIMARY KEY REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  result jsonb NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.advisor_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user','assistant')),
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_advisor_profile ON public.advisor_messages(profile_id, created_at);

CREATE TABLE IF NOT EXISTS public.advisor_conversations (
  id uuid PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  focus_type text NOT NULL DEFAULT 'general' CHECK (focus_type IN ('general','major','school')),
  focus_id bigint,
  focus_name text,
  title text NOT NULL,
  memory_summary text,
  summarized_through_message_id bigint,
  legacy_key text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_advisor_conversation_legacy UNIQUE (profile_id, legacy_key)
);
CREATE INDEX IF NOT EXISTS idx_advisor_conversation_profile ON public.advisor_conversations(profile_id, updated_at);

CREATE TABLE IF NOT EXISTS public.advisor_conversation_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id uuid NOT NULL REFERENCES public.advisor_conversations(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('user','assistant')),
  content text NOT NULL,
  client_message_id uuid,
  reply_to_message_id bigint,
  generation_status text CHECK (generation_status IN ('pending','complete','failed')),
  legacy_message_id bigint UNIQUE,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT uk_advisor_client_message UNIQUE (conversation_id, client_message_id)
);
CREATE INDEX IF NOT EXISTS idx_advisor_conversation_message ON public.advisor_conversation_messages(conversation_id, id);
CREATE INDEX IF NOT EXISTS idx_advisor_reply_message ON public.advisor_conversation_messages(reply_to_message_id);

CREATE TABLE IF NOT EXISTS public.source_artifacts (
  id uuid PRIMARY KEY,
  source_id bigint NOT NULL REFERENCES public.data_sources(id),
  official_page_url text NOT NULL,
  download_url text,
  mirror_url text,
  mirror_disclosure text,
  published_at date,
  collected_at timestamptz NOT NULL DEFAULT NOW(),
  sha256 text NOT NULL,
  local_path text NOT NULL,
  byte_size bigint NOT NULL,
  CONSTRAINT uk_source_artifact_checksum UNIQUE (source_id, sha256)
);

CREATE TABLE IF NOT EXISTS public.school_aliases (
  alias text PRIMARY KEY,
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  source_id bigint NOT NULL REFERENCES public.data_sources(id),
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','verified','rejected')),
  verified_at timestamptz,
  note text
);
CREATE INDEX IF NOT EXISTS idx_school_alias_target ON public.school_aliases(school_id, verification_status);
CREATE INDEX IF NOT EXISTS idx_school_alias_source ON public.school_aliases(source_id);

CREATE TABLE IF NOT EXISTS public.school_fact_audits (
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  fact_type text NOT NULL CHECK (fact_type IN ('official_website','admissions_website','featured_major','admission_coverage')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('verified','unavailable','not_applicable','pending')),
  reason text,
  source_url text,
  checked_at timestamptz,
  PRIMARY KEY (school_id, fact_type)
);
CREATE INDEX IF NOT EXISTS idx_school_fact_status ON public.school_fact_audits(fact_type, status);

CREATE TABLE IF NOT EXISTS public.admission_scope_audits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  province_id integer NOT NULL REFERENCES public.provinces(id),
  year smallint NOT NULL,
  education_level text NOT NULL CHECK (education_level IN ('本科','专科')),
  admission_category text NOT NULL DEFAULT '*',
  batch text NOT NULL DEFAULT '*',
  subject_group text NOT NULL DEFAULT '*',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('verified','unavailable','not_applicable','pending')),
  reason text,
  source_id bigint REFERENCES public.data_sources(id),
  checked_at timestamptz,
  CONSTRAINT uk_admission_scope_audit UNIQUE (province_id, year, education_level, admission_category, batch, subject_group)
);
CREATE INDEX IF NOT EXISTS idx_admission_scope_status ON public.admission_scope_audits(province_id, year, status);
CREATE INDEX IF NOT EXISTS idx_admission_scope_source ON public.admission_scope_audits(source_id);

CREATE TABLE IF NOT EXISTS public.school_featured_major_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_id bigint NOT NULL REFERENCES public.schools(id) ON DELETE CASCADE,
  major_id bigint REFERENCES public.majors(id) ON DELETE CASCADE,
  major_name text NOT NULL,
  major_code text,
  education_level text NOT NULL DEFAULT '本科' CHECK (education_level IN ('本科','高职')),
  recognition_type text NOT NULL,
  recognition_year smallint,
  source_id bigint NOT NULL REFERENCES public.data_sources(id),
  verified_at timestamptz NOT NULL,
  CONSTRAINT uk_featured_major_evidence UNIQUE NULLS NOT DISTINCT (school_id, major_name, recognition_type, recognition_year)
);
CREATE INDEX IF NOT EXISTS idx_featured_major_school ON public.school_featured_major_evidence(school_id, verified_at);
CREATE INDEX IF NOT EXISTS idx_featured_major_major ON public.school_featured_major_evidence(major_id);
CREATE INDEX IF NOT EXISTS idx_featured_major_source ON public.school_featured_major_evidence(source_id);

CREATE TABLE IF NOT EXISTS public.admission_unit_majors (
  admission_program_id bigint NOT NULL REFERENCES public.admission_programs(id) ON DELETE CASCADE,
  raw_major_name text NOT NULL,
  major_id bigint REFERENCES public.majors(id) ON DELETE SET NULL,
  source_id bigint NOT NULL REFERENCES public.data_sources(id),
  verification_status text NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending','verified','rejected')),
  verified_at timestamptz,
  PRIMARY KEY (admission_program_id, raw_major_name)
);
CREATE INDEX IF NOT EXISTS idx_aum_major ON public.admission_unit_majors(major_id, verification_status);
CREATE INDEX IF NOT EXISTS idx_aum_source ON public.admission_unit_majors(source_id);

CREATE TABLE IF NOT EXISTS public.import_batches (
  id uuid PRIMARY KEY,
  source_id bigint NOT NULL REFERENCES public.data_sources(id),
  artifact_id uuid REFERENCES public.source_artifacts(id),
  status text NOT NULL CHECK (status IN ('preflight','running','completed','failed','rolled_back')),
  report jsonb,
  inserted_count integer NOT NULL DEFAULT 0,
  updated_count integer NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_import_batches_source ON public.import_batches(source_id);
CREATE INDEX IF NOT EXISTS idx_import_batches_artifact ON public.import_batches(artifact_id);

CREATE TABLE IF NOT EXISTS public.admission_import_rows (
  batch_id uuid NOT NULL REFERENCES public.import_batches(id) ON DELETE CASCADE,
  source_row_number integer NOT NULL,
  record_key text,
  normalized_record jsonb,
  status text NOT NULL CHECK (status IN ('valid','duplicate','unmatched','rejected')),
  reason text,
  committed_program_id bigint REFERENCES public.admission_programs(id) ON DELETE SET NULL,
  PRIMARY KEY (batch_id, source_row_number)
);
CREATE INDEX IF NOT EXISTS idx_import_row_status ON public.admission_import_rows(batch_id, status);
CREATE INDEX IF NOT EXISTS idx_import_row_program ON public.admission_import_rows(committed_program_id);

CREATE TABLE IF NOT EXISTS public.admission_import_changes (
  batch_id uuid NOT NULL REFERENCES public.import_batches(id) ON DELETE CASCADE,
  record_key text NOT NULL,
  operation text NOT NULL CHECK (operation IN ('inserted','updated')),
  admission_program_id bigint NOT NULL REFERENCES public.admission_programs(id) ON DELETE CASCADE,
  previous_record jsonb,
  PRIMARY KEY (batch_id, record_key)
);
CREATE INDEX IF NOT EXISTS idx_import_change_program ON public.admission_import_changes(admission_program_id);

CREATE TABLE IF NOT EXISTS public.job_directions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  employment_category text NOT NULL,
  name text NOT NULL,
  aliases jsonb NOT NULL DEFAULT '[]'::jsonb,
  requires_postgraduate smallint NOT NULL DEFAULT 0 CHECK (requires_postgraduate IN (0,1)),
  requires_certificate smallint NOT NULL DEFAULT 0 CHECK (requires_certificate IN (0,1)),
  reviewed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_job_category ON public.job_directions(employment_category);

CREATE TABLE IF NOT EXISTS public.major_job_directions (
  major_id bigint NOT NULL REFERENCES public.majors(id) ON DELETE CASCADE,
  job_direction_id bigint NOT NULL REFERENCES public.job_directions(id) ON DELETE CASCADE,
  priority smallint NOT NULL CHECK (priority > 0),
  direct_entry smallint NOT NULL DEFAULT 1 CHECK (direct_entry IN (0,1)),
  review_status text NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending','approved','rejected')),
  PRIMARY KEY (major_id, job_direction_id),
  CONSTRAINT uk_major_job_priority UNIQUE (major_id, priority)
);
CREATE INDEX IF NOT EXISTS idx_major_job_direction ON public.major_job_directions(job_direction_id);

CREATE TABLE IF NOT EXISTS public.major_employment_profiles (
  major_id bigint PRIMARY KEY REFERENCES public.majors(id) ON DELETE CASCADE,
  nationwide_coverage_score numeric(5,2) NOT NULL DEFAULT 0,
  direct_entry_ratio numeric(5,2) NOT NULL DEFAULT 0,
  stability_score numeric(5,2),
  automation_risk_score numeric(5,2),
  evidence jsonb NOT NULL,
  stats_as_of date,
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.major_outlook_evidence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  major_id bigint NOT NULL REFERENCES public.majors(id) ON DELETE CASCADE,
  source_id bigint NOT NULL REFERENCES public.data_sources(id) ON DELETE CASCADE,
  signal_type text NOT NULL CHECK (signal_type IN ('digital_talent','industrial_transformation','public_service_demand','demographic_demand')),
  signal_level text NOT NULL CHECK (signal_level IN ('moderate','strong')),
  rationale text NOT NULL,
  reviewed_at date NOT NULL,
  valid_until date NOT NULL,
  CONSTRAINT uk_major_outlook_source_signal UNIQUE (major_id, source_id, signal_type)
);
CREATE INDEX IF NOT EXISTS idx_major_outlook_validity ON public.major_outlook_evidence(major_id, valid_until);
CREATE INDEX IF NOT EXISTS idx_major_outlook_source ON public.major_outlook_evidence(source_id);

CREATE TABLE IF NOT EXISTS public.job_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  source_type text NOT NULL CHECK (source_type IN ('official','public_platform','employer')),
  base_url text NOT NULL UNIQUE,
  access_policy_url text,
  collection_policy text NOT NULL,
  status text NOT NULL DEFAULT 'healthy' CHECK (status IN ('healthy','degraded','paused')),
  last_success_at timestamptz,
  last_failure_at timestamptz,
  failure_count integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.job_postings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fingerprint text NOT NULL,
  source_id bigint NOT NULL REFERENCES public.job_sources(id),
  job_direction_id bigint NOT NULL REFERENCES public.job_directions(id),
  employer text NOT NULL,
  title text NOT NULL,
  province text NOT NULL,
  city text NOT NULL,
  education text,
  published_at date NOT NULL,
  source_url text NOT NULL,
  collected_at timestamptz NOT NULL DEFAULT NOW(),
  expires_at date NOT NULL,
  CONSTRAINT uk_job_source_fingerprint UNIQUE (fingerprint, source_id)
);
CREATE INDEX IF NOT EXISTS idx_job_recent ON public.job_postings(published_at, job_direction_id, province);
CREATE INDEX IF NOT EXISTS idx_job_source ON public.job_postings(source_id);
CREATE INDEX IF NOT EXISTS idx_job_direction ON public.job_postings(job_direction_id);

CREATE TABLE IF NOT EXISTS public.job_daily_stats (
  stat_date date NOT NULL,
  major_id bigint NOT NULL REFERENCES public.majors(id) ON DELETE CASCADE,
  province text NOT NULL,
  job_count integer NOT NULL,
  source_count integer NOT NULL,
  PRIMARY KEY (stat_date, major_id, province)
);
CREATE INDEX IF NOT EXISTS idx_job_daily_major ON public.job_daily_stats(major_id);

CREATE TABLE IF NOT EXISTS public.profile_saved_items (
  profile_id uuid NOT NULL REFERENCES public.student_profiles(id) ON DELETE CASCADE,
  item_type text NOT NULL CHECK (item_type IN ('major','school')),
  item_id bigint NOT NULL,
  state text NOT NULL CHECK (state IN ('saved','excluded','target')),
  note text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY (profile_id, item_type, item_id)
);

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'schools','student_profiles','profile_assessments','profile_preferences',
    'advisor_conversations','major_employment_profiles','job_sources','profile_saved_items'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON public.%I', 'set_' || table_name || '_updated_at', table_name);
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at()', 'set_' || table_name || '_updated_at', table_name);
  END LOOP;
END;
$$;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'provinces','schools','majors','school_majors','admission_scores','admission_programs','student_profiles',
    'profile_score_snapshots','profile_assessments','profile_preferences','recommendation_results','recommendation_snapshots',
    'advisor_messages','advisor_conversations','advisor_conversation_messages','data_sources','source_artifacts','school_aliases',
    'school_fact_audits','admission_scope_audits','school_featured_major_evidence','admission_unit_majors','import_batches',
    'admission_import_rows','admission_import_changes','job_directions','major_job_directions','major_employment_profiles',
    'major_outlook_evidence','job_sources','job_postings','job_daily_stats','profile_saved_items'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated', table_name);
  END LOOP;
END;
$$;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;

INSERT INTO public.provinces(name, exam_mode, max_score) VALUES
  ('河南','3+1+2',750),
  ('山东','3+3',750),
  ('河北','3+1+2',750)
ON CONFLICT (name) DO UPDATE SET exam_mode=EXCLUDED.exam_mode,max_score=EXCLUDED.max_score;
